plugins {
	id 'net.fabricmc.fabric-loom' version "${loom_version}"
	id 'maven-publish'
	id 'com.diffplug.spotless' version "${spotless_version}"
	id 'checkstyle'
}

repositories {
	// Add repositories to retrieve artifacts from in here.
	// You should only use this when depending on other mods because
	// Loom adds the essential maven repositories to download Minecraft and libraries from automatically.
	// See https://docs.gradle.org/current/userguide/declaring_repositories.html
	// for more information about repositories.
}

sourceSets {
	testmod {
		compileClasspath += main.compileClasspath
		runtimeClasspath += main.runtimeClasspath
	}
}

loom {
	accessWidenerPath = file("src/main/resources/render-chest.classtweaker")

	decompilers {
		vineflower {
			options.put(
			// Makes lambda names easy to find for Mixins
			"mark-corresponding-synthetics", "1"
			)
		}
	}

	runs {
		testmodClient {
			client()
			displayName = "Testmod Client"
			sourceSet = "testmod"
		}

		configureEach {
			preferGradleTask = true
		}
	}
}

dependencies {
	// To change the versions see the gradle.properties file
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	implementation "net.fabricmc:fabric-loader:${project.loader_version}"
	testImplementation "net.fabricmc:fabric-loader-junit:${project.loader_version}"

	// Fabric API. This is technically optional, but you probably want it anyway.
	implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"

	// Test mod stuff
	testmodImplementation sourceSets.main.output
}

processResources {
	def version = project.version
	inputs.property "version", version

	filesMatching("fabric.mod.json") {
		expand "version": version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 25
}

java {
	// Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
	// if it is present.
	// If you remove this line, sources will not be generated.
	withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25
}

test {
	useJUnitPlatform()
}

jar {
	def projectName = project.name
	inputs.property "projectName", projectName

	from("LICENCE") {
		rename { "${it}_$projectName"}
	}
}

spotless {
	lineEndings = com.diffplug.spotless.LineEnding.UNIX

	java {
		importOrder('\\#', 'java', 'javax', 'org', 'com', '')
		removeUnusedImports()
		leadingSpacesToTabs()
		trimTrailingWhitespace()
		endWithNewline()
	}

	groovyGradle {
		target 'src/**/*.gradle', '*.gradle', 'gradle/*.gradle'
		greclipse().configProperties 'groovy.formatter.multiline.indentation=2', // Default
				'groovy.formatter.line.maxlength=999',
				'groovy.formatter.longListLength=999',
				'groovy.formatter.remove.unnecessary.semicolons=true'
	}
}

checkstyle {
	toolVersion = "${checkstyle_version}"
	configFile = rootProject.file("checkstyle.xml")
	configProperties = [
		"suppressionsFile": rootProject.file("checkstyle-suppressions.xml"),
		"cacheFile": layout.buildDirectory.file("checkstyle/checkstyle-cache.txt").get().asFile
	]
}

// configure the maven publication
publishing {
	publications {
		create("mavenJava", MavenPublication) {
			from components.java
		}
	}

	repositories {
		maven {
			url = "https://maven.azureaaron.net/releases"

			credentials(PasswordCredentials) {
				username = System.getenv("AARON_MAVEN_USER")
				password = System.getenv("AARON_MAVEN_PASS")
			}
		}
	}
}
